### ISSUE TITLE
[FEATURE] Compatibility with DnD 5E Version 4.0

### ISSUE THREAD

**Issue by SirAron111** [morepurplemorebetter/fvtt-items-with-spells-5e#6] opened 2024-09-19 15:57 UTC
## Describe the bug
Currently, module not compatible with DnD 5E anymore it seems at least with version 4.0 and up.

## Steps to reproduce
Get Module and DnD 5e.

## Versions
- Items with Spells: v12.1.1
- System: dnd5e v4.0+
- Foundry VTT: v12

## Additional context
Not sure if this is due to the update of the base system 5e or anything, but the module doesn't work or load anymore on 5e v4.0. If this is intended, I hope it will update to work sometime within the next few weeks.

**Comment by morepurplemorebetter** [comment] 2024-09-20 06:57
This module is marked as not compatible with dnd5e v4.x for a reason, it is not a bug. When the system changes, modules have to change along with it. The change from v3.x to v4.x is massive, so it will take some time for modules to be compatible. I'm working on it, but please be patient.

**Comment by morepurplemorebetter** [comment] 2024-09-28 19:05
As of v13.0.0, this module is now compatible with DnD5e v4.0.x
v12.2.0 is a version with bugfixes for those of us who are still on DnD5e v3.1.x (me included)

**Closed as completed by morepurplemorebetter** 2024-09-28 19:05 UTC
Labels: enhancement, planned
